spring.application.name=vocab-view
spring.datasource.url=${DB_NEON_URL}
spring.datasource.username=${DB_NEON_USERNAME}
spring.datasource.password=${DB_NEON_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE